// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8re2QKKGoGq6KrSymK3Mkp33YDhNi3bE',
    appId: '1:558256352013:web:02ede3a4847caa50469e44',
    messagingSenderId: '558256352013',
    projectId: 'food-delivery-720d7',
    authDomain: 'food-delivery-720d7.firebaseapp.com',
    storageBucket: 'food-delivery-720d7.appspot.com',
    measurementId: 'G-JFC7SDE1C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOXNVKW3QtWSiaj6S7fdEgaWpE5rFuO1M',
    appId: '1:558256352013:android:3f7d55855900255d469e44',
    messagingSenderId: '558256352013',
    projectId: 'food-delivery-720d7',
    storageBucket: 'food-delivery-720d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxbF78-kWt79saOm_-3sC5lvK39EMwXTA',
    appId: '1:558256352013:ios:a0bf4a929beff1ae469e44',
    messagingSenderId: '558256352013',
    projectId: 'food-delivery-720d7',
    storageBucket: 'food-delivery-720d7.appspot.com',
    iosBundleId: 'com.learning.vegiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxbF78-kWt79saOm_-3sC5lvK39EMwXTA',
    appId: '1:558256352013:ios:a0bf4a929beff1ae469e44',
    messagingSenderId: '558256352013',
    projectId: 'food-delivery-720d7',
    storageBucket: 'food-delivery-720d7.appspot.com',
    iosBundleId: 'com.learning.vegiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8re2QKKGoGq6KrSymK3Mkp33YDhNi3bE',
    appId: '1:558256352013:web:53c45853d9e3c940469e44',
    messagingSenderId: '558256352013',
    projectId: 'food-delivery-720d7',
    authDomain: 'food-delivery-720d7.firebaseapp.com',
    storageBucket: 'food-delivery-720d7.appspot.com',
    measurementId: 'G-QMVDYSTY2S',
  );
}
